#!/bin/bash
#
# Run RoMTEB across a fixed roster of models and aggregate.
#
#   bash scripts/run_all_models.sh
#
# Args:
#   $1              output dir (default: results)
#   $2..$N (opt)    task names to restrict to (default: run all tasks)
#  example: sbatch -A hria --gres=gpu:1 --partition=h200 -c 10 --mem-per-cpu=27G --job-name=register romteb/scripts/run_all_models.sh results_new RoNLIPairClassification  
# Notes:
#   - Cohere requires COHERE_API_KEY env var and the `cohere` Python package.
#   - jina-embeddings-v3 uses task-specific LoRA adapters; loaded via mteb
#     so MTEB can map each task type to the correct adapter automatically.
#   - Qwen3-Embedding-4B is large (4B params); ensure sufficient GPU memory.

set -euo pipefail
# Do not edit this file while a Slurm job is executing it. Bash keeps a
# byte offset into the file; a rewrite mid-run can execute a fragment
# (seen as `o: command not found`, exit 127) and abort the rest of the roster.

# Canonical tree is on project storage. Resolve it from this script's location
# so relative output paths (results, results_new) never land on $HOME.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)
cd "${ROOT}"

if ! nvidia-smi >/dev/null 2>&1; then
  echo "ERROR: no GPU on $(hostname). Dense encodes on the login node hang." >&2
  echo "  sbatch -A hria --gres=gpu:1 --partition=h200 -c 10 --mem-per-cpu=27G \\" >&2
  echo "    --job-name=romteb scripts/run_gpu_job.sh bash scripts/run_all_models.sh results" >&2
  exit 1
fi
nvidia-smi -L

OUTPUT_DIR=${1:-"${ROOT}/results"}
shift || true
RUNNER="${ROOT}/apptainer-exec-romteb.sh"
if [ ! -x "${RUNNER}" ]; then
  RUNNER="${ROOT}/../apptainer-exec-romteb.sh"
fi

TASK_ARGS=()
if [ "$#" -gt 0 ]; then
  TASK_ARGS=(--tasks "$@")
fi

# ── Helper ──────────────────────────────────────────────────────────────
run_model() {
  local MODEL="$1"
  local LOADER="${2:-auto}"
  local EXTRA_ARGS=()
  shift 2 || true
  while [ "$#" -gt 0 ]; do
    EXTRA_ARGS+=("$1")
    shift
  done
  echo
  echo "=== RoMTEB: ${MODEL}  (loader=${LOADER}) ==="
  ${RUNNER} "${ROOT}/romteb/run_benchmark.py" \
    --model "${MODEL}" \
    --output "${OUTPUT_DIR}" \
    --overwrite_results \
    --loader "${LOADER}" \
    "${EXTRA_ARGS[@]}" \
    "${TASK_ARGS[@]}" || echo "[WARN] ${MODEL} failed; continuing."
}

# ── SentenceTransformer models (loader=st) ──────────────────────────────
# run_model "intfloat/multilingual-e5-large"                              auto
# # run_model "alina0195/ro-retriever"                                      st
# # run_model "alina0195/robert-retriever"                                  st
# run_model "BAAI/bge-m3"                                                 st
# run_model "sentence-transformers/paraphrase-multilingual-mpnet-base-v2" st
# run_model "BlackKakapo/stsb-xlm-r-multilingual-ro"                     st
# run_model "iliemihai/romanian-sentence-bert-base-uncased-v1"            st
# run_model "sentence-transformers/LaBSE"                                 st
# # run_model "readerbench/RoBERT-large"                          st
# # run_model "readerbench/RoBERT-base"                          st
# # ModernBERT-based; flash_attn in the container is ABI-incompatible with PyTorch.
# run_model "ibm-granite/granite-embedding-97m-multilingual-r2" st --no_flash_attn
# # run_model "HIT-TMG/KaLM-embedding-multilingual-mini-v1"                          st
# run_model "Qwen/Qwen3-Embedding-4B"                            auto
# # run_model "jinaai/jina-embeddings-v4"                                 st

# Lexical baseline (CPU). Restricted to retrieval + reranking by the runner
# (LEXICAL_BASELINE_NAMES). BM25Search only implements index/search; --allow_cpu
# is required because BM25 doesn't use CUDA. Needed to identify trivially lexical
# tasks (XQuAD, MQARoCQA) and to flag dense models with wrong query prompts.
run_model "romteb/bm25s-ro"                                     auto --allow_cpu




# ══ TIER 0 — podeaua ═══════════════════════════════════════════════════
# Modelul folosit acum în faiss_indexer.py: max_seq_length=128, trunchiază
# pasajele de știri. Îl rulăm ca să documentăm de unde am plecat.
run_model "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"  st

# ══ TIER 1 — nucleul (100M–600M, deployabile) ══════════════════════════
# --- fără prompt ---
# Checkpoint-ul de bază pentru alina0195/bge-m3-ro-msmarco-v2 (fără prefix).
run_model "BAAI/bge-m3"                                          auto
run_model "Alibaba-NLP/gte-multilingual-base"                    st --trust_remote_code
# ModernBERT-based ca și 97m: același flag pentru flash_attn.
run_model "ibm-granite/granite-embedding-311m-multilingual-r2"   st --no_flash_attn

# --- cu prefixe "query: " / "passage: " (vezi nota de mai jos) ---
run_model "intfloat/multilingual-e5-small"                       auto
run_model "intfloat/multilingual-e5-base"                        auto

# --- cu instrucțiune / prefix pe query ---
# embeddinggemma: native ST prompts baked in ("task: search result | query: ");
# loader=auto -> mteb wrapper via PREFER_MTEB_LOADER so they are applied per
# task type. Loader=st also picks them up but is less explicit.
run_model "google/embeddinggemma-300m"                           auto
run_model "Qwen/Qwen3-Embedding-0.6B"                            auto
run_model "Snowflake/snowflake-arctic-embed-m-v2.0"              st --trust_remote_code
run_model "nomic-ai/nomic-embed-text-v2-moe"                     st --trust_remote_code


# ══ TIER 2 — plafonul (o rulare fiecare, nu intră în ablații) ══════════
run_model "intfloat/multilingual-e5-large-instruct"              auto
run_model "Qwen/Qwen3-Embedding-8B"                              auto
# bge-multilingual-gemma2: MTEB registry has use_instructions=False, but the
# model card recommends <instruct>...\n<query> on retrieval queries. Loader=st
# so our MODEL_PROMPTS query prompt is applied (loader=mteb would ignore it).
run_model "BAAI/bge-multilingual-gemma2"                         st
# nemotron: needs the LlamaEmbedNemotron wrapper (Instruct: {task}\nQuery:).
# loader=auto -> mteb via PREFER_MTEB_LOADER. Batch=1 due to 8B params on H200.
run_model "nvidia/llama-embed-nemotron-8b"                       auto --batch_size 1

# jina-v3: selecție de adaptor LoRA prin task=; licență CC-BY-NC (non-comercial) - cu prefix.
run_model "jinaai/jina-embeddings-v3"                            st --trust_remote_code
# OOM at batch=32 (WebFAQ, SciTechBan, SaRoCo, RoDTAL). Retry: --loader st
# --batch_size 1 --tasks WebFAQRetrieval SciTechBanROClassification
# SaRoCoClassification RoDTALLawsRetrieval. Listed in ROSTER.
# run_model "tencent/KaLM-Embedding-Gemma3-12B-2511"               auto


echo
echo "=== Aggregating ==="
${RUNNER} "${ROOT}/scripts/aggregate_results.py" --results_dir "${OUTPUT_DIR}"
